export default {
  defaultNote: 'Hello from the demo workspace.',
  workspace: 'WORKSPACE', tasks: 'My tasks', lab: 'Security lab', demo: 'Demo application', shared: 'Shared workspace', local: 'Demo environment',
  title: 'A little more organized.', subtitle: 'Your everyday tasks. A practical playground for OpenWAF.', total: 'Total tasks', pending: 'To do', completed: 'Completed', progress: 'Workspace progress',
  list: 'Task list', listHint: 'Make room for what matters.', add: 'Add task', taskPlaceholder: 'What needs to get done?', search: 'Search tasks…', all: 'All tasks', active: 'To do', done: 'Completed', high: 'High', medium: 'Medium', low: 'Low', priority: 'Priority', delete: 'Delete task', toggle: 'Toggle completion', empty: 'No tasks here. Add one or try another search.',
  labTitle: 'See the difference protection makes.', labSubtitle: 'Send the same requests directly and through OpenWAF. Compare the results in its request logs.', builtin: 'Built-in rules', labHint: 'Requests use the current origin. Open this workspace through the OpenWAF proxy to test protection.',
  sql: 'SQL injection', sqlDescription: 'Search is interpolated into a SQLite query. This payload reads a synthetic internal note from another table.', xss: 'Reflected XSS', xssDescription: 'The note preview renders raw HTML. This payload runs JavaScript and changes the preview content.', env: 'Environment exposure', envDescription: 'A public configuration file reveals a synthetic API key.', git: 'Git exposure', gitDescription: 'A public Git configuration reveals a synthetic repository URL.', run: 'Send request', running: 'Sending…', request: 'Request', response: 'Response', waiting: 'Choose a scenario and send a request.', blocked: 'Blocked with HTTP 403', reached: 'Origin responded', failed: 'Request failed', inspect: 'Check OpenWAF logs for the matched rule IDs.', preview: 'Live preview', previewHint: 'The preview runs in an isolated iframe.', note: 'Note preview', notePlaceholder: 'Write a note or HTML to preview…', openPreview: 'Preview note',
  footer: 'Built for demonstrating OpenWAF', synthetic: 'Synthetic data · resets on server restart', error: 'Could not complete the request.', status: 'HTTP status', language: 'Language', rule: 'Rule family', exposed: 'Exposure', theme: 'Toggle color theme', sqlFamily: 'CRS 942 · SQL injection', xssFamily: 'CRS 941 · Cross-site scripting', envFamily: 'OpenWAF 1001001', gitFamily: 'OpenWAF 1001003'
}
