import type en from './en'
const pl: Record<keyof typeof en, string> = {
  defaultNote: 'Witaj w przestrzeni demonstracyjnej.',
  workspace: 'PRZESTRZEŃ ROBOCZA', tasks: 'Moje zadania', lab: 'Laboratorium bezpieczeństwa', demo: 'Aplikacja demonstracyjna', shared: 'Wspólna przestrzeń', local: 'Środowisko demonstracyjne',
  title: 'Trochę więcej porządku.', subtitle: 'Twoje codzienne zadania. Praktyczny poligon dla OpenWAF.', total: 'Wszystkie zadania', pending: 'Do zrobienia', completed: 'Ukończone', progress: 'Postęp pracy',
  list: 'Lista zadań', listHint: 'Zrób miejsce na to, co ważne.', add: 'Dodaj zadanie', taskPlaceholder: 'Co trzeba zrobić?', search: 'Szukaj zadań…', all: 'Wszystkie', active: 'Do zrobienia', done: 'Ukończone', high: 'Wysoki', medium: 'Średni', low: 'Niski', priority: 'Priorytet', delete: 'Usuń zadanie', toggle: 'Zmień status zadania', empty: 'Brak zadań. Dodaj nowe lub zmień wyszukiwanie.',
  labTitle: 'Zobacz, co zmienia ochrona.', labSubtitle: 'Wyślij te same żądania bezpośrednio i przez OpenWAF. Porównaj wyniki w dzienniku żądań.', builtin: 'Wbudowane reguły', labHint: 'Żądania trafiają do bieżącego adresu aplikacji. Otwórz aplikację przez proxy OpenWAF, aby przetestować ochronę.',
  sql: 'SQL injection', sqlDescription: 'Wyszukiwanie jest wstawiane do zapytania SQLite. Ten ładunek odczytuje fikcyjną notatkę wewnętrzną z innej tabeli.', xss: 'Reflected XSS', xssDescription: 'Podgląd notatki renderuje surowy HTML. Ten ładunek uruchamia JavaScript i zmienia treść podglądu.', env: 'Ujawnienie środowiska', envDescription: 'Publiczny plik konfiguracji ujawnia fikcyjny klucz API.', git: 'Ujawnienie Git', gitDescription: 'Publiczna konfiguracja Git ujawnia fikcyjny adres repozytorium.', run: 'Wyślij żądanie', running: 'Wysyłanie…', request: 'Żądanie', response: 'Odpowiedź', waiting: 'Wybierz scenariusz i wyślij żądanie.', blocked: 'Zablokowano: HTTP 403', reached: 'Serwer odpowiedział', failed: 'Żądanie nie powiodło się', inspect: 'Sprawdź identyfikatory dopasowanych reguł w dzienniku OpenWAF.', preview: 'Podgląd na żywo', previewHint: 'Podgląd działa w izolowanej ramce iframe.', note: 'Podgląd notatki', notePlaceholder: 'Wpisz notatkę lub HTML do podglądu…', openPreview: 'Podgląd notatki',
  footer: 'Do demonstracji OpenWAF', synthetic: 'Fikcyjne dane · reset po restarcie serwera', error: 'Nie udało się wykonać żądania.', status: 'Status HTTP', language: 'Język', rule: 'Rodzina reguł', exposed: 'Ujawnienie danych', theme: 'Zmień motyw kolorystyczny', sqlFamily: 'CRS 942 · SQL injection', xssFamily: 'CRS 941 · Cross-site scripting', envFamily: 'OpenWAF 1001001', gitFamily: 'OpenWAF 1001003'
}
export default pl
